services:
  vectoshop-nginx:
    image: ghcr.io/sylvesterfox/vectoshop-nginx:${vectoshop_NGINX_IMAGE_TAG:-latest}
    container_name: vectoshop-nginx
    hostname: vectoshop-nginx
    restart: always
    env_file:
      - .env
    volumes:
      - ${NGINX_SSL_FULLCHAIN_PATH:-/opt/vectoshop/nginx/remnabot_fullchain.pem}:/etc/nginx/ssl/fullchain.pem:ro
      - ${NGINX_SSL_PRIVKEY_PATH:-/opt/vectoshop/nginx/remnabot_privkey.key}:/etc/nginx/ssl/privkey.key:ro
    ports:
      - "0.0.0.0:${NGINX_HTTPS_PORT:-443}:443"
    networks:
      - remnawave-network
    healthcheck:
      test: ["CMD-SHELL", "test -f /var/run/nginx.pid"]
      interval: 5s
      timeout: 3s
      retries: 3

  vectoshop-db:
    image: postgres:17
    container_name: "vectoshop-db"
    hostname: vectoshop-db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
      - TZ=UTC
    volumes:
      - vectoshop-db-data:/var/lib/postgresql/data
    networks:
      - remnawave-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 3s
      timeout: 10s
      retries: 3

  vectoshop-redis:
    image: valkey/valkey:9-alpine
    container_name: "vectoshop-redis"
    hostname: vectoshop-redis
    restart: unless-stopped
    command: ["--requirepass", "${REDIS_PASSWORD}", "--bind", "0.0.0.0"]
    volumes:
      - vectoshop-redis-data:/data
    networks:
      - remnawave-network
    healthcheck:
      test: ["CMD", "valkey-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 3s
      timeout: 10s
      retries: 3

  vectoshop:
    image: ghcr.io/sylvesterfox/vectoshop-backend:${vectoshop_IMAGE_TAG:-latest}
    container_name: "vectoshop"
    hostname: vectoshop
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "127.0.0.1:5000:5000"
    environment:
      RESET_ASSETS: "${RESET_ASSETS:-false}"
      UVICORN_RELOAD_ENABLED: "false"
    depends_on:
      vectoshop-nginx:
        condition: service_healthy
      vectoshop-db:
        condition: service_healthy
      vectoshop-redis:
        condition: service_healthy
    volumes:
      - ./logs:/opt/vectoshop/logs
      - ./assets:/opt/vectoshop/assets
    networks:
      - remnawave-network

  vectoshop-taskiq-worker:
    image: ghcr.io/sylvesterfox/vectoshop-backend:${vectoshop_IMAGE_TAG:-latest}
    container_name: "vectoshop-taskiq-worker"
    hostname: vectoshop-taskiq-worker
    restart: unless-stopped
    command: taskiq worker src.infrastructure.taskiq.worker:worker --tasks-pattern src/infrastructure/taskiq/tasks -fsd
    env_file:
      - .env
    environment:
      RESET_ASSETS: "${RESET_ASSETS:-false}"
    depends_on:
      vectoshop:
        condition: service_started
    volumes:
      - ./logs:/opt/vectoshop/logs
      - ./assets:/opt/vectoshop/assets
    networks:
      - remnawave-network

  vectoshop-taskiq-scheduler:
    image: ghcr.io/sylvesterfox/vectoshop-backend:${vectoshop_IMAGE_TAG:-latest}
    container_name: "vectoshop-taskiq-scheduler"
    hostname: vectoshop-taskiq-scheduler
    restart: unless-stopped
    command: taskiq scheduler src.infrastructure.taskiq.scheduler:scheduler --tasks-pattern src/infrastructure/taskiq/tasks -fsd
    env_file:
      - .env
    environment:
      RESET_ASSETS: "${RESET_ASSETS:-false}"
    depends_on:
      vectoshop:
        condition: service_started
    volumes:
      - ./logs:/opt/vectoshop/logs
      - ./assets:/opt/vectoshop/assets
    networks:
      - remnawave-network


networks:
  remnawave-network:
    name: remnawave-network
    external: false

volumes:
  vectoshop-db-data:
    name: ${vectoshop_DB_VOLUME_NAME:-vectoshop-db-data}
  vectoshop-redis-data:
    name: ${vectoshop_REDIS_VOLUME_NAME:-vectoshop-redis-data}
